Driver=ODBC Driver 18 for SQL Server
Server=tcp:databaseproject6test.database.windows.net,1433
Database=databaseproject6final
User=CloudSA9847f5c
Password=Admin056

Encrypt=yes
TrustServerCertificate=no
Timeout=30